// The reader-state entry points.
//
// A first-time visitor lands on a library of forty frameworks and has no way
// to know which three matter to them. These pages answer that, and nothing
// else. They contain no new writing about markets or property: every item is
// an existing framework, calculator or glossary term, referenced by slug and
// rendered from the arrays themselves. If a slug is renamed, pathstest.mjs
// fails the build rather than shipping a dead link.
//
// Each path carries exactly one `intent`, which must be one of INTENTS in
// src/lib.mjs. That is the value the gated form sends to MailerLite as
// Investor Intent, and it is what routes a new subscriber into one of the
// four email tracks. Inventing a seventh intent here would create a
// subscriber who matches no segment and therefore receives nothing, so the
// test asserts the mapping both ways.

export default [
  {
    slug: "first-property",
    intent: "Buy my first investment property",
    label: "Buy my first investment property",
    title: "Buying your first investment property",
    blurb: "The arithmetic that decides whether a listing is worth an offer, in the order you need it.",
    lede: "Almost every first purchase goes wrong in the same place: the advertised yield is a gross yield, and the costs that turn it into a net one are not in the listing. Work through these in order and you will price a property the way its eventual buyer will, rather than the way its seller does.",
    order: [
      "net-rental-yield",
      "the-one-percent-rule",
      "transaction-cost-drag",
      "service-charge-and-reserves",
      "due-diligence-before-an-offer",
      "off-plan-vs-ready",
      "mortgage-vs-cash",
      "break-even-occupancy",
    ],
    calculators: ["net-rental-yield", "rent-vs-buy"],
    terms: [
      "gross-rental-yield",
      "net-rental-yield",
      "service-charge",
      "transfer-fee",
      "oqood",
      "escrow-account",
      "no-objection-certificate",
      "snagging",
    ],
    close: "If you read one of these, read the first. It is the calculation most owners have never run on a property they already hold.",
  },
  {
    slug: "growing-a-portfolio",
    intent: "Add to an existing property portfolio",
    label: "Add to a property portfolio",
    title: "Adding to a property portfolio you already own",
    blurb: "Yield on the next unit, the rent you are allowed to charge, and when to sell instead.",
    lede: "The second purchase is a different problem from the first. You are no longer asking whether property works; you are asking whether this unit beats the one you already own, what the rental index will let you charge, and whether the answer is to buy nothing and sell something.",
    order: [
      "cash-on-cash",
      "cap-rate",
      "rent-increase-caps",
      "break-even-occupancy",
      "short-let-vs-long-let",
      "price-per-square-foot",
      "concentration-limits",
      "off-plan-irr",
      "selling-well",
    ],
    calculators: ["net-rental-yield", "dubai-rent-increase", "off-plan-irr"],
    terms: [
      "cash-on-cash-return",
      "loan-to-value",
      "debt-service-coverage-ratio",
      "void-period",
      "minimum-hold-period",
      "payment-plan",
      "handover",
    ],
    close: "The concentration framework is the one owners skip and later wish they had not. Several units in one tower is one bet, not several.",
  },
  {
    slug: "global-portfolio",
    intent: "Build a global markets portfolio",
    label: "Build a global markets portfolio",
    title: "Building a global markets portfolio",
    blurb: "What to hold, in what proportion, and the domicile decision that quietly costs the most.",
    lede: "The hard part is not choosing funds. It is deciding what the portfolio is for, holding the proportions through a year you would rather not, and getting the structural decisions right at the start, because domicile and fee drag compound in exactly the way returns do.",
    order: [
      "what-diversification-does",
      "asset-allocation-by-horizon",
      "three-fund-portfolio",
      "what-bonds-are-for",
      "fund-domicile",
      "fee-drag",
      "rebalancing-bands",
      "sequence-of-returns",
      "lump-sum-vs-dca",
    ],
    calculators: ["lump-sum-vs-dca", "safe-withdrawal-rate", "estate-tax-exposure"],
    terms: [
      "index-fund",
      "expense-ratio",
      "accumulating-vs-distributing",
      "fund-domicile",
      "withholding-tax",
      "tracking-difference",
      "rebalancing",
      "correlation",
    ],
    close: "Read the domicile framework before you buy anything. It is the only item on this list that is expensive to fix afterwards.",
  },
  {
    slug: "diversifying",
    intent: "Diversify out of a single market",
    label: "Diversify out of one market",
    title: "Diversifying out of a single market",
    blurb: "What concentration actually costs, and what a second market does and does not fix.",
    lede: "Most portfolios that feel diversified are one bet wearing several names: one city, one currency, one employer, one asset class. These frameworks are about measuring that honestly first, because a second holding that moves with the first has not reduced anything.",
    order: [
      "concentration-limits",
      "what-diversification-does",
      "currency-risk-and-the-peg",
      "property-vs-index-funds",
      "price-to-rent",
      "dubai-vs-london",
      "drawdown-recovery-math",
      "inflation-and-real-returns",
      "emergency-liquidity",
    ],
    calculators: ["lump-sum-vs-dca", "net-rental-yield"],
    terms: [
      "home-bias",
      "correlation",
      "drawdown",
      "volatility-drag",
      "real-yield",
      "breakeven-inflation",
      "sequence-of-returns-risk",
    ],
    close: "The drawdown arithmetic is short and worth knowing by heart. Recovering from a fall is not symmetrical with the fall.",
  },
  {
    slug: "relocating",
    intent: "Relocate or set up in the UAE",
    label: "Relocate or set up in the UAE",
    title: "Relocating to, or setting up in, the UAE",
    blurb: "Currency, succession, ownership structure and the reserve you actually need.",
    lede: "Moving countries changes the structure of a portfolio more than its contents. The questions that matter are which currency your liabilities are in, who inherits what under which law, whether assets should sit in your name at all, and how much cash a move genuinely requires.",
    order: [
      "currency-risk-and-the-peg",
      "uae-wills-and-succession",
      "corporate-vs-personal-ownership",
      "fund-domicile",
      "emergency-liquidity",
      "rent-vs-buy",
      "the-primary-residence",
      "insurance-and-its-gaps",
    ],
    calculators: ["rent-vs-buy", "estate-tax-exposure", "dubai-rent-increase"],
    terms: [
      "tax-residency",
      "situs",
      "us-estate-tax",
      "double-tax-treaty",
      "freehold",
      "leasehold",
      "title-deed",
    ],
    close: "Succession is the one people postpone. A will drafted where you live and assets held where you used to live is the common and expensive combination.",
  },
  {
    slug: "learning",
    intent: "Just learning",
    label: "I am just learning",
    title: "Starting from the beginning",
    blurb: "The ideas the rest of the library takes for granted, in the order that makes each one explain the next.",
    lede: "Nothing here assumes you own anything or intend to buy anything soon. These are the ideas the rest of the library takes for granted, chosen because each one changes how you read the next thing you come across, on this site or anywhere else.",
    order: [
      "what-diversification-does",
      "net-rental-yield",
      "fee-drag",
      "inflation-and-real-returns",
      "what-bonds-are-for",
      "the-behaviour-gap",
      "sunk-cost-and-selling",
      "reverse-the-assumption",
    ],
    calculators: ["net-rental-yield", "lump-sum-vs-dca"],
    terms: [
      "gross-rental-yield",
      "index-fund",
      "expense-ratio",
      "basis-point",
      "drawdown",
      "yield-curve",
      "real-yield",
    ],
    close: "The last one is a habit rather than a formula, and it is the most useful thing on this page.",
  },
];
