#!/usr/bin/env node
/* Produces one pasteable file for the Cloudflare dashboard.
 
   The Worker is written as three modules so the schema and the entry
   format are shared with the site's own build rather than duplicated.
   Cloudflare's dashboard editor takes a single file, so this inlines
   them. It is a deliberately dumb concatenator: no bundler, no
   dependency, and it refuses rather than guesses if it meets anything
   it does not understand. */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const ENTRY = path.join(root, "admin/worker.js");
const OUT = path.join(root, "admin/worker.bundled.js");

const IMPORT = /^import\s*\{([^}]+)\}\s*from\s*["'](\.[^"']+)["'];?\s*$/gm;

const seen = new Set();
function inline(file) {
  const src = fs.readFileSync(file, "utf8");
  const parts = [];
  let rest = src.replace(IMPORT, (whole, names, rel) => {
    const target = path.resolve(path.dirname(file), rel);
    if (!fs.existsSync(target)) throw new Error(`${path.relative(root, file)} imports ${rel}, which does not exist`);
    if (!seen.has(target)) {
      seen.add(target);
      parts.push(`/* ---- inlined from ${path.relative(root, target)} ---- */\n${inline(target)}`);
    }
    return "";
  });
  // Strip the export keyword; everything ends up in one scope.
  rest = rest.replace(/^export\s+(const|function|class|let)\s/gm, "$1 ");
  rest = rest.replace(/^export\s*\{[^}]*\};?\s*$/gm, "");
  return parts.join("\n\n") + "\n" + rest;
}

const bundled = inline(ENTRY);

if (/^\s*import\s/m.test(bundled)) {
  const line = bundled.split("\n").find((l) => /^\s*import\s/.test(l));
  throw new Error(`An import survived bundling, so the file would not run: ${line.trim()}`);
}
if (!/export default\s*\{/.test(bundled)) throw new Error("The bundle has no default export, so Cloudflare would not run it");

fs.writeFileSync(
  OUT,
  `/* GENERATED. Do not edit this file.
   Built from admin/worker.js by scripts/build-admin.mjs.
   Paste this whole file into the Cloudflare Worker editor. */

${bundled}`
);

console.log(`admin/worker.bundled.js  ${(fs.statSync(OUT).size / 1024).toFixed(0)}KB, ${bundled.split("\n").length} lines`);
